// <auto-generated />
using System;
using DotNetCore_New.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCore_New.Migrations
{
    [DbContext(typeof(CollegeDBContext))]
    [Migration("20250101170415_AddDataToStudentsTable")]
    partial class AddDataToStudentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetCore_New.Data.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("studentsDBTable");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DOB = new DateTime(1995, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentEmail = "saketkumar180@gmail.com",
                            StudentName = "Saket Jha",
                            StudentPhone = "9177881115"
                        },
                        new
                        {
                            StudentId = 2,
                            DOB = new DateTime(1994, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentEmail = "subhamsingh@gmail.com",
                            StudentName = "Subham singh",
                            StudentPhone = "8437074075"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
